### ISSUE TITLE
中文开发者加我微信 qq123862905 进讨论群

### ISSUE THREAD

**Issue by vipzrx** [abforce/xposed_art_n#12]
@abforce please do not close this issue ， it is for Chinese developers  not for you . You can not read Chinese ，so this issue will not disturb you.

0 我想先把abforce的这个xposed先编译起来，有兴趣的可以一起来。 aosp源码编译，手机适配、xposed移植 xposed模块的适配。一个人力量有限，希望大家加入 @IMISSOOXX @mzfqy @msg7086 @phxnirvana  @aviraxp @peterpei2001 @chanssl @fkzhang @wuxianlin

习惯使用github交流的，可以来这里 
https://github.com/vipzrx/xposed4N

1 xposed关注很久，abforce的这个项目也是早早就开始跟进，感谢作者@abforce的付出

2 很多人说这是issue 不是论坛，我觉得这种理解很狭隘，关注重点有失偏颇。只要是和这个项目有关系的，不一定非要是发现了什么bug，围绕xposed移植到android n上的话题都可以讨论。甚至给别人发的issue点了向下的拇指，我觉得这种行为并不好。

3 我看到很多人都在国内，我是做微信插件开发的，需要xposed，想搞个微信群，交流方便些，同时为那些中文不太好的人，做一些翻译工作。翻译过程，本身也是对自己理解是否正确的一种验证。

4 作者和很多人一直强调这是一个英文的项目，从很多issue来看，很多中文的issue提交者的issue来看，他们没有理解、或者理解有偏差，可见看英文的资料还是会有误解，有个中文的，经过验证和大家改进的文档，也是需要的。

**Comment by KeJunMao** [comment]
非英文的issue会被直接关闭吧- -

**Comment by vipzrx** [comment]
@KeJunMao 是的 我翻译的一个中文的README 也被直接关闭了。也是服了 理由是这是一个英文的项目。 linux的源码都没这么傲娇
https://github.com/abforce/xposed_art_n/pull/8

> 

Sorry, this project is in English. I can't merge your PR.
--

**Comment by KeJunMao** [comment]
> Sorry, this project is in English. I can't merge your PR.

既然他都说了，何必执着。

就像[提問的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)中说的，最好用英文

**Comment by phxnirvana** [comment]
if u want a Chinese one, u could fork one and do anything u want rather than continuously add useless issues

**Comment by msg7086** [comment]
Sorry this is **his** repo and **his** space. Never should he obey your command. Whether he shall close this topic, or whatever he wants, is on **his** discretion, not yours. If you want to make some contribution, fork it, or maybe build a Chinese website around the project.

Please also **do not** @ myself again. I don't use wechat, nor am I interested on your proposal.

Thank you for your effort though, but please note that *gone* doesn't translate as *go ahead*.

**Comment by chanssl** [comment]
Thanks, but I don't want to join any groups. 

Then, you can fork it and translation in your forked repo but not pull requests to this repo.

ps. I think that is a basic etiquette to use English for asking questions in English project and can make more people try to help you.

**Comment by vipzrx** [comment]
@phxnirvana   i do not want to rebuild a Chinese one , just want to add some Chinese documents in this repo

@msg7086 pls give a correct translation about **gone** here  in more details . And if you find more better or more accurate translation about my copy README_cn.md  , pls tell me . Thank you ! I just make a start , we can make it better and better together

@chanssl I used to use Chinese just becasue i have seen the issue reporter's profile and noticed that they are Chinese.  maybe Chinese is more efficient to communicate.  Thank you for your advice . i will use english more here from now.

**Comment by balthild** [comment]
As a Chinese, shame on you.

**Comment by WordlessEcho** [comment]
This issue is not about the repo, and you are disturbing people by at them.
In fact, it's more suitable to publish it in somewhere like V2EX.
The title and text with this issue are not good.

**Comment by aviraxp** [comment]
@abforce lock this issue plz.
