### ISSUE TITLE
How do you expect to handle modules? 

### ISSUE THREAD

**Issue by ashoksoni** [abforce/xposed_art_n#15]
So I build one from the modified art and other required files but xposed installer still shows no xposed framework installed. I didn't test further with any modules. How does it work, the handling of modules etc? Is there any way to know that the framework is installed or not other than the xposed installer. 

My builds are dex-preopt, so you think that could be a coz and I should build one this disabled?

**Comment by aviraxp** [comment]
No. Xposed installer recognize a file called xposed.repo to determine if Xposed is installed. Check the original Xposed installing zip for details.

**Comment by aviraxp** [comment]
Ah, no, xposed.prop

**Comment by abforce** [comment]
As @aviraxp stated, you should have a `xposed.prob` in `/system`.

**Comment by ashoksoni** [comment]
Thanks to your both. Did that, rom is fine now. Just have to figure out the list of working modules and if there is any other negative effects.
