### ISSUE TITLE
How to handle the third step

### ISSUE THREAD

**Issue by ghost** [abforce/xposed_art_n#19]
The third step is "Create a prebuilt module that copies XposedBridge.jar to system/framework, or manually copy it and run make snod to include it in the system.img." and I'm confused that how to do it. I skip this step and when I flashed the ROM, there is no XposedBridge.jar in System/framework and no xposed.prop in System. I manually copy the xposed.prop and XposedBridge.jar to the System and then it worked. I wonder that how to perfect it so that everything can be done after the completion of the ROM flash.

**Comment by aviraxp** [comment]
You can push them in vendors and use Makefile to copy it, just like other vendor files.

**Comment by ghost** [comment]
@aviraxp oh, thanks and I think that will be worked, but is there any other solution?

**Comment by djfeng** [comment]
excuse me ,yes or no xp for MIUI android 7.0 ?

**Comment by abforce** [comment]
@xiaoleservice Create a directory in `prebuilts/misc/common` called `XposedBridge` and copy `XposedBridge.jar` to it. Then create an `Android.mk` with the following content:

```
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := XposedBridge
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := XposedBridge.jar
LOCAL_MODULE_CLASS := JAVA_LIBRARIES
LOCAL_MODULE_SUFFIX := $(COMMON_JAVA_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)
```

And as the last step, edit `build/target/product/base.mk` and add `XpsoedBridge` to `PRODUCT_PACKAGES` variable.

This way, when you run `make` at the root of AOSP, make system automatically includes that `XposedBridge.jar` to `system/framework`. That's it.

**Comment by ghost** [comment]
@abforce I see. I did that yesterday, but I haven't tried to recompile it. By the way, will the `xposed.prop` be in the System directory after this?

**Comment by abforce** [comment]
No, to copy `xposed.prob` to the final image, you can add it to `PROCUDT_COPY_FILES`.

**Comment by ghost** [comment]
@abforce Got it, Thanks.👍
