### ISSUE TITLE
Boot loop

### ISSUE THREAD

**Issue by rahulkadavil** [abforce/xposed_art_n#22]
I replace the art folder and app_process from original AOSP and build it. When trying to open emulator it's in bootloop. I'm using source code for android 7.0 is it the problem? 

This is the output of logcat
 natctrl_tether_counters) res=1
08-07 04:54:19.636   998   998 V NatController: runCmd(/system/bin/iptables -w -N natctrl_tether_counters) res=0
08-07 04:54:19.644   998   998 V NatController: runCmd(/system/bin/iptables -w -t mangle -A natctrl_mangle_FORWARD -p tcp --tcp-flags SYN SYN -j TCPMSS --clamp-mss-to-pmtu) res=0
08-07 04:54:19.710   998   998 W netd    : type=1400 audit(0.0:6): avc: denied { module_request } for kmod="netdev-dummy0" scontext=u:r:netd:s0 tcontext=u:r:kernel:s0 tclass=system permissive=0
08-07 04:54:19.717   998   998 E Netd    : cannot find interface dummy0
08-07 04:54:19.719   998   998 D MDnsDS  : MDnsSdListener::Hander starting up
08-07 04:54:19.720   998  1223 D MDnsDS  : MDnsSdListener starting to monitor
08-07 04:54:19.720   998  1223 D MDnsDS  : Going to poll with pollCount 1
08-07 04:54:20.023   989   989 I ServiceManager: Waiting for service media.camera.proxy...
08-07 04:54:21.033   989   989 I ServiceManager: Waiting for service media.camera.proxy...
08-07 04:54:21.273   988  1026 W BatteryNotifier: batterystats service unavailable!
08-07 04:54:22.044   989   989 I ServiceManager: Waiting for service media.camera.proxy...
08-07 04:54:23.053   989   989 I ServiceManager: Waiting for service media.camera.proxy...

**Comment by abforce** [comment]
Official Xposed for Android 7.0 has been released by @rovo89. This repo is not stable, so please go with the official one. BTW, your logcat doesn't show any errors related to this Xposed port.

**Comment by rahulkadavil** [comment]
I got an error while working with that 
'out/host/linux-x86/obj/SHARED_LIBRARIES/libart_intermediates/export_includes', needed by 'out/host/linux-x86/obj/EXECUTABLES/dexlist_intermediates/import_includes', missing and no known rule to make it
make: *** [ninja_wrapper] Error 1

**Comment by rahulkadavil** [comment]
Can you please tell me the way to Integrate xposed  with AOSP, I replace art folder and app_process folder with xposed one but still it bootloops

**Comment by abforce** [comment]
Start with the [official Xposed](https://github.com/rovo89/android_art) and investigate its commits on the original art. To build a built-in enabled Xposed ROM, you should keep all those commits except commits related to the _recompiling_ dex files. In such a ROM, nothing is going to be recompiled.

For Android M, I did it, and it worked fine and flawlessly, for N I'm not sure though. If you decide to do it, I also would like to be informed of your progress.

**Comment by rahulkadavil** [comment]
I'm working on that only but after building there is no libxposed_art.so and app_process of xposed file generated as well it bootloop with same error as shown above. Should we use xposedtools after building the AOSP and run ./build?

**Comment by rahulkadavil** [comment]
Is it something like xposed only works in arm not in x86
