### ISSUE TITLE
About XP

### ISSUE THREAD

**Issue by a1412847801** [abforce/xposed_art_n#3]
Hello I'm from China. I like you very much. I don't know what that means because of my network or website problem, but I just want to ask when it can be used I can't wait.

**Comment by chanssl** [comment]
Issues is not forums, Please create an issue when you have a problem with feedback, instead of creating a meaningless reply.

**Comment by vipzrx** [comment]
@a1412847801 @chanssl  我看下你们的资料，都是中国人。 却一直在讲英语。
我是学习微信插件开发，有个xposed开发的群，欢迎大家来讨论交流
加我微信 qq123862905 备注 xposed

**Comment by chanssl** [comment]
@vipzrx This is an English project.

**Comment by vipzrx** [comment]
@chanssl i do not want to argue with you .  maybe you can  find there are 5 peope talk about issue ， 3 or 4 people are in China
