### ISSUE TITLE
Old one or have to build new one? 

### ISSUE THREAD

**Issue by ashoksoni** [abforce/xposed_art_n#6]
Create a prebuilt module that copies XposedBridge.jar to system/framework.

This is the third step in read me however I am confused as whether we have to use the existing XposedBridge.jar or build a new one and if so, there isn't much info about that here. 

Will appreciate if you could shed some lights on that too. Thanks.

**Comment by aviraxp** [comment]
Just heads up, you may need to clear the whole data and cache partition with the new art library. There are some oat files there.

**Comment by ashoksoni** [comment]
Thanks for the heads up. Will keep that in mind. You managed to run this up?

**Comment by vipzrx** [comment]
@ashoksoni  you should rebuild a new XposedBridge.jar  by replace the frameworks/base/cmds/app_process of rovo89 with the  abforce‘s version
 
Replace original art/ submodule with this copy.
Replace original frameworks/base/cmds/app_process with the modified one.

**Comment by ashoksoni** [comment]
According to this, https://github.com/rovo89/XposedBridge/issues/115 this is something else. I think I need to build from this repo to get XposedBridge along with replacing the original one with this one.

**Comment by abforce** [comment]
> Will appreciate if you could shed some lights on that too. Thanks.

There's a `XposedBridge.jar` that should be placed in `system/framework`. No matter how to do this, using a prebuilt module, manually copying it, etc.

Please note that I've not changed `XposedBridge.jar` at all. So, you don't need to compile it from source.

**Comment by hellobbn** [comment]
@abforce 
That is: you just used the XposedBridge.jar from the old Xposed installation zip?

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 OnePlus ONEPLUS A3000 发送_
