### ISSUE TITLE
aosp支持7.1.2的手机清单如下

### ISSUE THREAD

**Issue by vipzrx** [abforce/xposed_art_n#9]
Driver Binaries for Nexus and Pixel Devices  |  Google APIs for Android  |  Google Developers
https://developers.google.com/android/drivers

![20170718_233937](https://user-images.githubusercontent.com/5094958/28326211-b678e5ba-6c12-11e7-8d96-b771b9bc3c38.png)

**Comment by kotomei** [comment]
Issues is not forums, Please create an issue when you have a problem with feedback, instead of creating a meaningless reply.

**Comment by a1412847801** [comment]
全是谷歌亲儿子
